### ISSUE TITLE
Can't run typescript tests calls rust methods

### ISSUE THREAD

**Issue by ZhaoXiangXML** [Vaults/threets-rust-wasm-template#24]
I've add a test like this:

```typescript
import { assert } from "chai";
import { add } from "../../src/ts/util"
import * as rustWASM from '../../target/pkg'

describe("Index", () => {
    it("trivial pass", () => {
        assert.equal(add(1,2), 3);
    });
    it("wasm", ()=>{
        assert.equal(rustWASM.get_color(), "#F5D742");
    });
});
```

However when I run the tests I got this error:
```
Error: Could not find source file: 'C:/Projects/test/threets-rust-wasm-template-master/target/pkg/index_bg.wasm'.
    at getValidSourceFile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\typescript\lib\typescript.js:139148:29)
    at Object.getEmitOutput (C:\Projects\test\threets-rust-wasm-template-master\node_modules\typescript\lib\typescript.js:139533:30)
    at getOutput (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:562:32)
    at Object.compile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Projects\test\threets-rust-wasm-template-master\target\pkg\index_bg.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Projects\test\threets-rust-wasm-template-master\target\pkg\index.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Projects\test\threets-rust-wasm-template-master\tests\ts\util.test.ts:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Projects\test\threets-rust-wasm-template-master\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\esm-utils.js:28:26)
    at Mocha.loadFilesAsync (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\mocha.js:386:19)
    at singleRun (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\cli\run-helpers.js:149:15)
    at exports.runMocha (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\cli\run-helpers.js:186:11)
    at Object.exports.handler (C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\lib\cli\run.js:319:11)
    at C:\Projects\test\threets-rust-wasm-template-master\node_modules\mocha\node_modules\yargs\lib\command.js:241:49
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run test" terminated with exit code: 1.
```

Would you please help me out with it, thank you.

Also, is it possible to run the tests within a browser?

**Comment by Vaults** [comment]
Hi, apologies for the late response and thank you for submitting an issue! I don't check my github often. Since it has been a long time, I wouldn't know how to import the wasm into the context of Mocha, the template was hard to set up and highly experimental. I could spend some time trying to figure that out if this is absolutely necessary for you though.

There is another way to do integration tests, check web.rs, `npm run integration-test`. It imports the rust wasm into a browser and runs tests on the wasm only. I hope that has been helpful for you, if not, let me know.

**Comment by ZhaoXiangXML** [comment]
Thank you for your kind reply, I've figured it out myself at https://github.com/ZhaoXiangXML/threets-rust-wasm-template.
